In [1]:
import pandas as pd
import numpy as np

industry = pd.read_csv("../data/industry_dataset.csv")
syllabus = pd.read_csv("../data/syllabus_dataset.csv")

industry.head()

  Company  Year               Role            Skill    Skill_Type
0  Oracle  2021  Backend Developer             Java   Traditional
1  Oracle  2021  Backend Developer      Spring Boot  Transitional
2  Oracle  2021  Backend Developer              SQL  Transitional
3  Oracle  2021  Software Engineer             Java   Traditional
4  Oracle  2021  Software Engineer  Data Structures  Transitional

In [2]:
industry['Skill'] = industry['Skill'].str.lower().str.strip()
syllabus['Skill'] = syllabus['Skill'].str.lower().str.strip()

industry['Year'] = pd.to_numeric(industry['Year'])

industry['Upcoming_Flag'] = (
    industry['Skill_Type'].str.lower() == 'upcoming'
).astype(int)

industry.head()

,Company,Year,Role,Skill,Skill_Type,Upcoming_Flag
0,Oracle,2021,Backend Developer,java,Traditional,0
1,Oracle,2021,Backend Developer,spring boot,Transitional,0
2,Oracle,2021,Backend Developer,sql,Transitional,0
3,Oracle,2021,Software Engineer,java,Traditional,0
4,Oracle,2021,Software Engineer,data structures,Transitional,0

In [3]:
industry.to_csv("../outputs/cleaned_industry.csv", index=False)